site_name: PyIndexRepo

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python

theme:
  name: readthedocs
  features:
    - navigation.expand
    - toc.integrate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 5

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - API reference: 'api.md'