site_name: Fast Refractive Index
theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: true